apiVersion: v1
kind: Namespace
metadata:
  name: c2c-ship-sync-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-ship-sync-deployment
  namespace: c2c-ship-sync-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:8a6fc48537040655b8001b711eb15d9b0fe6a985

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-ship-sync-label
  name: c2c-ship-sync-service
  namespace: c2c-ship-sync-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---